# Generated by Django 2.2.3 on 2019-07-26 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ciudad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='municipios',
            table='Municipios',
        ),
        migrations.AlterModelTable(
            name='regiones',
            table='Regiones',
        ),
    ]
