# Generated by Django 2.2.3 on 2019-07-26 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ciudad', '0002_auto_20190725_1948'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='municipios',
            table='municipios',
        ),
        migrations.AlterModelTable(
            name='regiones',
            table='regiones',
        ),
    ]
