# Generated by Django 2.2.3 on 2019-07-26 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ciudad', '0003_auto_20190725_1949'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='municipios',
            table=None,
        ),
        migrations.AlterModelTable(
            name='regiones',
            table=None,
        ),
    ]
