# Generated by Django 2.2.3 on 2019-07-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ciudad', '0004_auto_20190725_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Municipios',
        ),
        migrations.AlterField(
            model_name='region',
            name='municipios',
            field=models.ManyToManyField(blank=True, to='Ciudad.Municipio'),
        ),
        migrations.AlterModelTable(
            name='region',
            table='Region',
        ),
        migrations.RenameModel(
            old_name='Regiones',
            new_name='Region',
        ),
    ]
